import assert from "node:assert/strict";
import { layoutText, cellForOffset, offsetForCell, editPage, newNotebook, newPage, pageLayoutOptions, normalizeBookshelf, validateNotebook, changePaper, countText } from "../lib/notebook.ts";
const rules = { manuscript: true };
const visible = text => layoutText(text, rules).chars.filter(c => !c.hidden);
assert.equal(layoutText("", rules).caret, 1);
assert.equal(layoutText("", rules).used, 0);
assert.deepEqual(visible("가나\n다").map(c => c.cell), [1, 2, 26]);
assert.equal(visible(" 가")[0].cell, 1);
assert.equal(visible("가".repeat(25)).at(-1).cell, 25);
assert.equal(visible("가\n\n나").at(-1).cell, 51);
assert.deepEqual(visible("2026abcDE").map(c => c.cell), [1, 1, 2, 2, 3, 3, 4, 5, 6]);
assert.equal(cellForOffset("2026", 1, rules), 1.5);
assert.equal(offsetForCell("2026", 1.5, rules), 1);
assert.equal(cellForOffset("가나\n다", 3, rules), 26);
for (const punctuation of [".", ",", "!", "?", "”", ")"]) {
  const glyphs = visible("가".repeat(24) + punctuation);
  assert.equal(glyphs.at(-1).cell, 24);
  assert.equal(layoutText("가".repeat(24) + punctuation, rules).used, 25);
}
assert.equal(visible("가".repeat(23) + "“나”").find(c => c.char === "“").cell, 25);
assert.equal(visible("“" + "가".repeat(24) + "”").filter(c => c.char === "가").at(-1).cell, 26);
assert.equal(visible("“가.”").at(-1).cell, visible("“가.”").at(-2).cell);
assert.deepEqual(visible("......").map(c => c.cell), [1, 1, 1, 2, 2, 2]);
assert.deepEqual(visible("…….").map(c => c.cell), [1, 2, 3]);
assert.equal(visible("가―나")[1].width, 2);
assert.equal(visible("왜?가").at(-1).cell, 4);
assert.equal(visible("왜? 가").at(-1).cell, 4);
assert.equal(visible("가. 나").at(-1).cell, 3);
assert.equal(countText("가. 나"), 4);
const unicode = "가👩‍💻🇰🇷e\u0301";
assert.equal(visible(unicode).length, 4);
assert.equal(visible(unicode).map(c => c.char).join(""), unicode);
let result = editPage(newNotebook(), 0, "가".repeat(1201), 1201);
assert.ok(result.accepted);
assert.equal(result.notebook.pages[1].continued, true);
assert.equal(layoutText(result.notebook.pages[1].text, pageLayoutOptions(result.notebook, 1)).chars[0].cell, 0);
assert.equal(result.notebook.pages.map(p => p.text).join(""), "가".repeat(1201));
assert.ok(validateNotebook(result.notebook));
result = editPage(newNotebook(), 0, "가\n".repeat(49), 98);
assert.equal(layoutText(result.notebook.pages[1].text, pageLayoutOptions(result.notebook, 1)).chars[0].cell, 1);
result = editPage(newNotebook(), 0, "2".repeat(2400), 2400);
assert.ok(result.accepted);
assert.equal(result.notebook.pages[0].text.length, 2398);
assert.equal(result.notebook.pages.map(p => p.text).join("").length, 2400);
const ink = [{ id: "ink", color: "#282a2c", width: 2, points: [{ x: .2, y: .3, p: .5 }] }];
const legacyPage = (text, id = "old-page") => ({ id, type: "manuscript", text, strokes: ink });
const legacy = { title: "기존 제목", pages: [legacyPage("가".repeat(1200))] };
const converted = normalizeBookshelf(legacy).books[0];
assert.equal(converted.title, legacy.title);
assert.equal(converted.pages[0].id, legacy.pages[0].id);
assert.equal(converted.pages[0].strokes[0].points[0].y, .3 * 40 / 48);
assert.equal(converted.pages[0].inkRows, 48);
assert.equal(normalizeBookshelf({ books: [converted] }).books[0], converted);
assert.equal(converted.pages.map(p => p.text).join(""), legacy.pages[0].text);
assert.equal(converted.pages.length, 2);
assert.ok(validateNotebook(converted));
const fullLegacy = { title: "12장 기존 글", pages: Array.from({ length: 12 }, (_, i) => legacyPage("가".repeat(1200), String(i))) };
const preserved = normalizeBookshelf(fullLegacy).books[0];
assert.deepEqual(preserved.pages.map(p => [p.id, p.text]), fullLegacy.pages.map(p => [p.id, p.text]));
assert.equal(preserved.pages[0].strokes[0].points[0].y, .3 * 40 / 48);
const realOldPage = { ...legacyPage("가".repeat(1000)), typesetting: 1 };
const old1000 = normalizeBookshelf({ title: "기존 1000칸", pages: [realOldPage] }).books[0];
assert.equal(old1000.pages.length, 1);
assert.equal(old1000.pages[0].text, realOldPage.text);
assert.equal(old1000.pages[0].strokes[0].points[0].y * 48, .3 * 40);
assert.ok(validateNotebook(fullLegacy));
const blank = { title: "", pages: [{ ...newPage("blank"), text: "가".repeat(1200), strokes: ink }] };
const changed = changePaper(blank, 0, "manuscript");
assert.ok(changed.accepted);
assert.equal(changed.notebook.pages.length, 2);
assert.deepEqual(changed.notebook.pages[0].strokes, ink);
assert.ok(validateNotebook(changed.notebook));
const fullBlank = { title: "", pages: Array.from({ length: 12 }, () => ({ ...newPage("blank"), text: "가".repeat(1200) })) };
assert.equal(changePaper(fullBlank, 0, "manuscript").accepted, false);
assert.equal(changePaper(fullBlank, 0, "manuscript").notebook, fullBlank);
console.log("Manuscript checks passed: paragraphs, punctuation, paired digits/letters, ellipses, cursor, page continuation, atomic migration and ink preservation.");
